version: '3.7'

services:
  minio:
   image: myminio
   container_name: minio
   ports:
     - "9000:9000"
     - "9090:9090"
   environment:
     MINIO_ROOT_USER: minioadmin
     MINIO_ROOT_PASSWORD: minioadmin
   volumes:
     - data:/data
   command: minio server ~/minio --console-address :9090
   restart: unless-stopped
volumes:
    data:
